const p = require("node:path");
const fs = require("node:fs");
const esbuild = require("esbuild");
const { glob } = require("glob");

const fsp = fs.promises;

async function main() {
  const workers = await glob("src/**/*.worker.ts");
  const define = {};
  for (const worker of workers) {
    const out = await esbuild.build({
      entryPoints: [worker],
      bundle: true,
      minify: true,
      outfile: p.join("dist", p.basename(worker, ".worker.ts") + ".worker.js"),
      platform: "node",
      write: false,
    });
    define[`WORKERS.${p.basename(worker, ".worker.ts").toUpperCase()}`] =
      JSON.stringify(out.outputFiles[0].text);
  }

  const tests = await glob("src/**/*.test.ts");
  const master = tests
    .map((name) => p.relative("src", name))
    .map((name) => name.replaceAll(p.sep, p.posix.sep))
    .sort()
    .map((name) => `import "./${name}";`);

  master.unshift(
    "// This file was autogenerated while building tests. Do not edit manually",
  );
  master.push("");

  const masterName = p.join("src", "tests.ts");
  await fsp.writeFile(masterName, master.join("\n"));

  await esbuild.build({
    entryPoints: [masterName],
    outfile: p.join("dist", "tests.js"),
    bundle: true,
    minify: true,
    sourcemap: true,
    platform: "node",
    define,
  });
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
