:toc:
:toc-title:
:toclevels: 1

ifdef::env-github[]
:note-caption: :information_source:
endif::[]

= https://adventofcode.com/2024[Advent of Code 2024^] solver

== Usage

=== Install dependencies

```bash
npm ci
```

=== Build

```bash
npm run typecheck && npm run build
```

=== Run

```bash
node dist/aoc-2024.js -d <day> -i <input file>
```

=== Test

```bash
npm test
```

NOTE: Only a few modules are covered by tests. That's more of a sanity check than proper coverage.

== List of puzzles

NOTE: I have no idea if day 17 part 2 will work for arbitrary input.
This puzzle is about reverse-engineering and a lot of assumptions
are based around my input.

[%header,cols="70,~,~,~",format=csv]
|===
Day,Part I,Part II,Execution time
Day 1: Historian Hysteria,✅,✅,2ms
Day 2: Red-Nosed Reports,✅,✅,6ms
Day 3: Mull It Over,✅,✅,1ms
Day 4: Ceres Search,✅,✅,64ms
Day 5: Print Queue,✅,✅,13ms
Day 6: Guard Gallivant,✅,✅,486ms
Day 7: Bridge Repair,✅,✅,200ms
Day 8: Resonant Collinearity,✅,✅,2ms
Day 9: Disk Fragmenter,✅,✅,178ms
Day 10: Hoof It,✅,✅,12ms
Day 11: Plutonian Pebbles,✅,✅,41ms
Day 12: Garden Groups,✅,✅,716ms
Day 13: Claw Contraption,✅,✅,2ms
Day 14: Restroom Redoubt,✅,✅,260ms
Day 15: Warehouse Woes,✅,✅,35ms
Day 16: Reindeer Maze,✅,✅,1192ms
Day 17: Chronospatial Computer,✅,✅,1ms
Day 18: RAM Run,✅,✅,24ms
Day 19: Linen Layout,✅,✅,92ms
Day 20: Race Condition,✅,✅,206ms
Total,,,3533ms
|===

== Full-test mode

Create `.csv` file with a list of inputs/answers, formatted like that:

```csv
1,day-1.txt,420,69
2,day-2.txt,690,42
...
```

where columns are

1. Day number (number)
2. Input file location, *relative to `.csv` file location*
3. Answer for part 1 (number)
4. Answer for part 2 (number)

Then build project as described

```bash
npm run typecheck && npm run build
```

And run full-test

```bash
node dist/aoc-2024.js -f <csv file location>
```
